import Home from './Home';
import ContactUs from './ContactUs';
// import Shop from "./Shop";
import Cart from './Cart';
import AboutUs from './AboutUs';
import UserAcount from './UserAcount';
import ProductPage from './ProductPage';
import SearchPage from './SearchPage';
import Error404 from './Error404';
export { Home, ContactUs, Cart, AboutUs, UserAcount, ProductPage,SearchPage,Error404};
