import Home from './Home';
import ContactUs from './ContactUs';
import Shop from "./Shop";
import Cart from './Cart';
import AboutUs from './AboutUs';
import UserAccount from "./UserAccount";
import ProductPage from './ProductPage';
import SearchPage from './SearchPage';
import Error404 from './Error404';
export { Home, ContactUs, Cart, AboutUs, UserAccount, ProductPage,SearchPage,Error404,Shop};
